# Setup mold for faster linking
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[alias]
dyn-build = "build --features bevy/dynamic_linking"
dyn-run = "run --features bevy/dynamic_linking"

[build]
rustc-wrapper = "sccache"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
